## Deliverable 2. Create a Customer Travel Destinations Map.

In [3]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config1 import gkey

# Configure gmaps API key
gmaps.configure(api_key=gkey)

In [4]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,city,lat,lng,max_temp,humidity,cloudiness,wind_speed,country,date,description
0,0,Busselton,-33.6500,115.3333,78.01,55,0,3.00,AU,2021-01-22 00:57:48,clear sky
1,1,Alekseyevsk,57.8406,108.3492,-17.77,86,100,1.88,RU,2021-01-22 00:57:48,overcast clouds
2,2,Port Alfred,-33.5906,26.8910,64.99,95,0,10.25,ZA,2021-01-22 00:57:48,clear sky
3,3,Port Elizabeth,-33.9180,25.5701,68.00,94,90,9.22,ZA,2021-01-22 00:57:49,fog
4,4,Iqaluit,63.7506,-68.5145,32.00,69,75,25.32,CA,2021-01-22 00:55:09,snow

In [5]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_tempur = float(input("What is the minimum temperature you would like for your trip? "))
max_tempur = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 20
What is the maximum temperature you would like for your trip? 50

In [6]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df.max_temp <= max_tempur)&
                                      (city_data_df.max_temp >= min_tempur)]

In [7]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isna().sum()

City_ID        0
city           0
lat            0
lng            0
max_temp       0
humidity       0
cloudiness     0
wind_speed     0
country        0
date           0
description    0
dtype: int64

In [8]:
# 4b. Drop any empty rows and create a new DataFrame that doesnâ€™t have empty rows.
clean_df= preferred_cities_df.dropna()

In [9]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["city", "country", "max_temp", "description", "lat", "lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,city,country,max_temp,description,lat,lng,Hotel Name
4,Iqaluit,CA,32.00,snow,63.7506,-68.5145,
9,Albany,US,33.01,scattered clouds,42.6001,-73.9662,
11,Kodiak,US,42.80,moderate rain,57.7900,-152.4072,
17,Iqaluit,CA,32.00,snow,63.7506,-68.5145,
22,Albany,US,33.01,scattered clouds,42.6001,-73.9662,
24,Kodiak,US,42.80,moderate rain,57.7900,-152.4072,
35,Andenes,NO,21.20,overcast clouds,69.3143,16.1194,
36,Jamestown,US,35.01,light rain,42.0970,-79.2353,
41,Port Hardy,CA,41.00,scattered clouds,50.6996,-127.4199,
43,Torbay,CA,30.99,snow,47.6666,-52.7314,

In [10]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": gkey
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["lat"]
    lng = row["lng"]
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    params["location"] = f"{lat},{lng}"
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        print("Found")
    except:
        print("Not Found, next")

Found
Not Found, next
Found
Found
Not Found, next
Found
Found
Found
Found
Found
Found
Not Found, next
Found
Not Found, next
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Not Found, next
Found
Not Found, next
Found
Found
Found
Found
Found
Found
Found
Not Found, next
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Not Found, next
Found
Found
Found
Found
Found
Found
Found
Found
Not Found, next
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Not Found, next
Not Found, next
Found
Found
Not Found, next
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Not Found, next
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found
Found

In [11]:
# 7. Drop the rows where there is no Hotel Name.
cleaned_hotel_df = hotel_df.dropna()
cleaned_hotel_df

,city,country,max_temp,description,lat,lng,Hotel Name
4,Iqaluit,CA,32.00,snow,63.7506,-68.5145,Frobisher Inn
9,Albany,US,33.01,scattered clouds,42.6001,-73.9662,
11,Kodiak,US,42.80,moderate rain,57.7900,-152.4072,Best Western Kodiak Inn and Convention Center
17,Iqaluit,CA,32.00,snow,63.7506,-68.5145,Frobisher Inn
22,Albany,US,33.01,scattered clouds,42.6001,-73.9662,
...,...,...,...,...,...,...,...
673,Sisimiut,GL,20.62,clear sky,66.9395,-53.6735,Hotel Sisimiut
675,Lexington,US,39.99,clear sky,37.9887,-84.4777,DoubleTree Suites by Hilton Hotel Lexington
677,Madison,US,46.00,mist,34.7334,-86.5667,Embassy Suites by Hilton Huntsville Hotel & Spa
678,Payson,US,43.00,clear sky,40.0444,-111.7321,Quality Inn Payson I-15
679,Mehriz,IR,32.00,haze,31.5917,54.4318,Mehrgard dwelling/Ø³Ø±Ø§ÛŒ Ù…Ù‡Ø±Ú¯Ø±Ø¯

In [ ]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
cleaned_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [ ]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{city}</dd>
<dt>Country</dt><dd>{country}</dd>
<dt>Max Temp</dt><dd>{max_temp} Â°F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in cleaned_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = cleaned_hotel_df[["lat", "lng"]]

In [ ]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig